name: 'Build ArchLinux Packages'
description: 'Build an ArchLinux package in Docker container'
branding:
  icon: user-check
  color: gray-dark
inputs:
  pkg-name:
    description: 'ArchLinux package name to build'
    required: true
    default: 'wps-office'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pkg-name }}
