name: 'Build AUR Package'
description: 'Test build an AUR package in Docker container'
branding:
  icon: user-check
  color: gray-dark
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
    default: 'linux-ck-uksm'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
